const actions = {
    ADD_USER : "ADD_USER",
    REMOVE_USER : "REMOVE_USER",
    CHANGE_SEARCH_TEXT : "CHANGE_SEARCH_TEXT",
    CHANGE_SEARCH_PAGE : "CHANGE_SEARCH_PAGE",
    INCREMENT_SEARCH_PAGE : "INCREMENT_SEARCH_PAGE"
}

export default actions